version: '3.8'
services:
  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  # Optional: local Kafka (Zookeeper + Kafka) for development
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  app:
    build: .
    depends_on:
      - redis
      - mysql
      - kafka
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Allow overriding the JDBC URL from the environment; keep a reasonable default that points to the mysql service in compose
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/paging_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
      # Simple defaults are provided for local development; use a .env file to supply real credentials.
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-paging_user1}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-paging_pass1}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8080:8080"
    command: ["java","-Dspring.profiles.active=prod","-jar","/app/app.jar"]

  mysql:
    image: mysql:8.0
    environment:
      # Root password and user credentials must be supplied via environment variables or a .env file.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-paging_db}
      MYSQL_USER: ${MYSQL_USER:-paging_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data:

